### ISSUE TITLE
"when backdrop switches to backdrop1when loudness >10"

### ISSUE THREAD

**Issue by dtplsongithub** [Ponali/scratch-3ds#3]
![image](https://github.com/Ponali/scratch-3ds/assets/153951662/48944c1e-5842-43df-9e32-665313eb3282)
thats all i have to say

**Comment by WahPlus** [comment]
yeah i encountered this before but didnt know how to fix it so... ponali this is your problem now

**Comment by Ponali** [comment]
i have found a fix, and i have a hypothesis for it: every string must end with a NUL character at the end so C knows that the string has ended and processes the scanned string. however, "when backdrop switches to backdrop1" actually is too large that a NUL character can't be put: making it go to the next string while scanning, and processes the concated string instead. the fix is to increase the maximum height of the strings from 35 to 36.
this has now been fixed in a recent commit.

**Comment by dtplsongithub** [comment]
okey 👍
